font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  size: 12.0
import:
   - ~/.config/alacritty/themes/themes/tokyo-night.yaml
window:
  option_as_alt: OnlyLeft
  padding:
    x: 6
    y: 6
key_bindings:
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
